# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/u4bi_/_Mac/Study/OSS_TeamProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/u4bi_/_Mac/Study/OSS_TeamProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/u4bi_/_Mac/Study/OSS_TeamProject/CMakeFiles /Users/u4bi_/_Mac/Study/OSS_TeamProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/u4bi_/_Mac/Study/OSS_TeamProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyCExecutable

# Build rule for target.
MyCExecutable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyCExecutable
.PHONY : MyCExecutable

# fast build rule for target.
MyCExecutable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/build
.PHONY : MyCExecutable/fast

2048/2048.o: 2048/2048.c.o
.PHONY : 2048/2048.o

# target to build an object file
2048/2048.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/2048/2048.c.o
.PHONY : 2048/2048.c.o

2048/2048.i: 2048/2048.c.i
.PHONY : 2048/2048.i

# target to preprocess a source file
2048/2048.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/2048/2048.c.i
.PHONY : 2048/2048.c.i

2048/2048.s: 2048/2048.c.s
.PHONY : 2048/2048.s

# target to generate assembly for a file
2048/2048.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/2048/2048.c.s
.PHONY : 2048/2048.c.s

BrickBreaker/Brickbreaker.o: BrickBreaker/Brickbreaker.c.o
.PHONY : BrickBreaker/Brickbreaker.o

# target to build an object file
BrickBreaker/Brickbreaker.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/BrickBreaker/Brickbreaker.c.o
.PHONY : BrickBreaker/Brickbreaker.c.o

BrickBreaker/Brickbreaker.i: BrickBreaker/Brickbreaker.c.i
.PHONY : BrickBreaker/Brickbreaker.i

# target to preprocess a source file
BrickBreaker/Brickbreaker.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/BrickBreaker/Brickbreaker.c.i
.PHONY : BrickBreaker/Brickbreaker.c.i

BrickBreaker/Brickbreaker.s: BrickBreaker/Brickbreaker.c.s
.PHONY : BrickBreaker/Brickbreaker.s

# target to generate assembly for a file
BrickBreaker/Brickbreaker.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/BrickBreaker/Brickbreaker.c.s
.PHONY : BrickBreaker/Brickbreaker.c.s

MineSweeper/Minesweeper.o: MineSweeper/Minesweeper.c.o
.PHONY : MineSweeper/Minesweeper.o

# target to build an object file
MineSweeper/Minesweeper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/MineSweeper/Minesweeper.c.o
.PHONY : MineSweeper/Minesweeper.c.o

MineSweeper/Minesweeper.i: MineSweeper/Minesweeper.c.i
.PHONY : MineSweeper/Minesweeper.i

# target to preprocess a source file
MineSweeper/Minesweeper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/MineSweeper/Minesweeper.c.i
.PHONY : MineSweeper/Minesweeper.c.i

MineSweeper/Minesweeper.s: MineSweeper/Minesweeper.c.s
.PHONY : MineSweeper/Minesweeper.s

# target to generate assembly for a file
MineSweeper/Minesweeper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/MineSweeper/Minesweeper.c.s
.PHONY : MineSweeper/Minesweeper.c.s

Tetris/Tetris.o: Tetris/Tetris.c.o
.PHONY : Tetris/Tetris.o

# target to build an object file
Tetris/Tetris.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/Tetris/Tetris.c.o
.PHONY : Tetris/Tetris.c.o

Tetris/Tetris.i: Tetris/Tetris.c.i
.PHONY : Tetris/Tetris.i

# target to preprocess a source file
Tetris/Tetris.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/Tetris/Tetris.c.i
.PHONY : Tetris/Tetris.c.i

Tetris/Tetris.s: Tetris/Tetris.c.s
.PHONY : Tetris/Tetris.s

# target to generate assembly for a file
Tetris/Tetris.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/Tetris/Tetris.c.s
.PHONY : Tetris/Tetris.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyCExecutable.dir/build.make CMakeFiles/MyCExecutable.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyCExecutable"
	@echo "... 2048/2048.o"
	@echo "... 2048/2048.i"
	@echo "... 2048/2048.s"
	@echo "... BrickBreaker/Brickbreaker.o"
	@echo "... BrickBreaker/Brickbreaker.i"
	@echo "... BrickBreaker/Brickbreaker.s"
	@echo "... MineSweeper/Minesweeper.o"
	@echo "... MineSweeper/Minesweeper.i"
	@echo "... MineSweeper/Minesweeper.s"
	@echo "... Tetris/Tetris.o"
	@echo "... Tetris/Tetris.i"
	@echo "... Tetris/Tetris.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

